### ISSUE TITLE
Model in solution to Exercise 9.2 likely uses unphysical features of the dataset

### ISSUE THREAD

**Issue by nikoladze** [DeepLearningForPhysicsResearchBook/deep-learning-physics#1]
As a follow up from the Deep Learning School 2 weeks ago where we used the RNN exercises from this repository i had a closer look at the solution to Exercise 9.2. The accuracy the model achieves is a bit suspiciously high, also the loss history which typically shows a sudden drop somewhen during training after 10-30 epochs.

What i found is that the model likely makes use of very specific amplitude values in the background simulations - that get then shifted once signal is added. An indication that this may be possible is that there are "only" around 500k individual floating point numbers in the background dataset while there are around 2.5 million in total. Maybe there was some loss of precision during preprocessing.

You can find an [explanatory notebook in my fork of this repository](https://github.com/nikoladze/deep-learning-physics/blob/investigate-09_2_solution/investigate_model.ipynb). The simplemost test involves randomly scaling each amplitude value within 1% - this should not be physically meaningful. However, in my tests this changed a prediction close to 0 (background) to a prediction close to 1 (signal).

A possible solution would be to do this random scaling during the training or preprocessing or to modify the dataset itself (needs to be evaluated how much is necessary to avoid this effect).

**Comment by jglombitza** [comment]
Many thanks for pointing out this issue. I just created a new dataset that should not suffer from this loss in precision anymore.
